# Generated by Django 4.2.3 on 2023-09-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('score_4', models.IntegerField()),
            ],
        ),
    ]
